
service: backend-car-rental
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpPort: 3003
  dynamodb:
    start:
      port: 5000
      inMemory: true
      migrate: true
    stages:
      - dev

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    USERS_TABLE: Users-${self:provider.stage}
    ITEMS_TABLE: Items-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: [
          "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USERS_TABLE}",
          "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.ITEMS_TABLE}"
      ]

functions:
  createUser:
    handler: src/users/functions/createUser.handler
    events:
      - http:
          method: post
          path: users
          cors: true
  getAllUser:
    handler: src/users/functions/getAllUsers.handler
    events:
      - http:
          method: get
          path: users
          cors: true
  getUser:
    handler: src/users/functions/getUser.handler
    events:
      - http:
          method: get
          path: users/{userId}
          cors: true
  updateUser:
    handler: src/users/functions/updateUser.handler
    events:
      - http:
          method: put
          path: users/{userId}
          cors: true
  deleteUser:
    handler: src/users/functions/deleteUser.handler
    events:
      - http:
          method: delete
          path: users/{userId}
          cors: true
  createItem:
    handler: src/items/functions/createItem.handler
    events:
      - http:
          method: post
          path: items
          cors: true
  getAllItems:
    handler: src/items/functions/getAllItems.handler
    events:
      - http:
          method: get
          path: items
          cors: true
  getItem:
    handler: src/items/functions/getItem.handler
    events:
      - http:
          method: get
          path: items/{itemId}
          cors: true
  updateItem:
    handler: src/items/functions/updateItem.handler
    events:
      - http:
          method: put
          path: items/{itemId}
          cors: true
  deleteItem:
    handler: src/items/functions/deleteItem.handler
    events:
      - http:
          method: delete
          path: items/{itemId}
          cors: true

resources:
  Resources:
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
    ItemsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.ITEMS_TABLE}
        AttributeDefinitions:
          - AttributeName: itemId
            AttributeType: S
        KeySchema:
          - AttributeName: itemId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
